from django.db import models
from django.utils import timezone


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, help_text="URL-friendly identifier (e.g., grok-vs-chatgpt)")
    content = models.TextField(help_text="HTML content generated by write-a-blog command")
    comparison_keyword = models.CharField(max_length=200, help_text="Original keyword like 'X vs Y'")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'Blog Posts'

    def __str__(self):
        return self.title
